{
	den.aspects.hyprland = {
		nixos = {
			programs.hyprland.enable = true;
		};

		homeManager = {
			config,
			pkgs,
			...
		}: {
			home.packages = with pkgs; [
				hyprcursor
				hyprpicker
				hyprpolkitagent
				hyprshot
				xdg-desktop-portal-hyprland
				xdg-desktop-portal-wlr
			];

			services.hyprpolkitagent.enable = true;

			services.hypridle = {
				enable = true;
				settings = {
					general = {
						lock_cmd = "pidof hyprlock || hyprlock";
						before_sleep_cmd = "loginctl lock-session";
						after_sleep_cmd = "hyprctl dispatch dpms on";
					};
					listener = [
						{
							# lock after 5 minutes
							timeout = 300;
							on-timeout = "loginctl lock-session";
						}
						{
							# turn display off after 10 minues
							timeout = 600;
							on-timeout = "hyprctl dispatch dpms off";
							on-resume = "hyprctl dispatch dpms on";
						}
					];
				};
			};

			services.hyprsunset = {
				enable = true;
				settings.profile = [
					{
						time = "18:00";
						temperature = 2500;
					}
					{
						time = "08:00";
						identity = true;
					}
				];
			};

			programs.hyprlock = {
				enable = true;
				settings = {
					general = {
						grace = 1;
						hide_cursor = true;
						ignore_empty_input = true;
					};
					background = {
						blur_size = 5;
						blur_passes = 1;
						noise = 0.0177;
						contract = 1.3000;
						brightness = 0.8000;
						vibrancy = 0.2100;
						vibrancy_darkness = 0.0;
					};
					label = {
						text = "MATOO";
						font_size = 25;
						position = "0, 155";
					};
					input-field = {
						size = "300, 50";
						outline_thickness = 3;
						dots_size = 0.33;
						dots_spacing = 0.15;
						dots_center = true;
						outer_color = "rgba(0,0,0,1)";
						inner_color = "rgba(255,255,255,1)";
						font_color = "rgba(0,100,255,1)";
						fade_on_empty = false;
						placeholder_text = "<i>password...</i>";
						hide_input = false;
						position = "0, 100";
						halign = "center";
						valign = "center";
					};
				};
			};

			wayland.windowManager.hyprland = {
				enable = true;
				xwayland.enable = true;
				# some of this syntax is for a more recent version of hyprland
				settings = {
					# general
					"autogenerated" = "0";

					# monitors
					monitor = [
						"DP-2,2560x1440@165,auto,1.2" # desktop primary
						"DP-3,2560x1440@75,auto-left,1.2" # desktop secondary
						"eDP-1,preferred,auto,1.75" # laptop
						"DP-4,preferred,auto-up,1.25" # laptop external
					];
					debug.disable_scale_checks = true;

					# programs
					"$terminal" = "kitty";
					"$fileManager" = "nautilus";
					"$menu" = "sherlock";

					# autostart
					exec-once = [
						"hyprctl dispatch workspace 1"
						"waybar"
						"hypridle"
						"hyprsunset"
						"discover-overlay"
						"kdeconnect-indicator"
						"~/Documents/kanata-tray-linux"
						"[workspace 6 silent] firefox"
						"[workspace 7 silent] discord"
					];

					# environment variables
					env = [
						"XCURSOR_SIZE,24"
						"HYPRCURSOR_SIZE,24"
						# XDG_MENU_PREFIX,arch-" # fix empty open-with in dolphin
						"MANGOHUD,0" # enable mangohud for all vulkan games
						"QT_AUTO_SCREEN_SCALE_FACTOR,1" # automatically scale qt windows based on monitor DPI
					];

					# look and feel
					general = {
						gaps_in = 5;
						gaps_out = 0;
						border_size = 2;
						"col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
						"col.inactive_border" = "rgba(595959aa)";
						allow_tearing = false;
						layout = "dwindle";
					};

					decoration = {
						rounding = 10;
						rounding_power = 2;
						active_opacity = 1.0;
						inactive_opacity = 1.0;
						shadow = {
							enabled = true;
							range = 4;
							render_power = 3;
							color = "rgba(1a1a1aee)";
						};
						blur = {
							enabled = true;
							size = 3;
							passes = 1;
							vibrancy = 0.1696;
						};
					};

					animations = {
						enabled = true;
						bezier = [
							"easeOutQuint, 0.23, 1, 0.32, 1"
							"easeInOutCubic, 0.65, 0.05, 0.36, 1"
							"linear, 0, 0, 1, 1"
							"almostLinear, 0.5, 0.5, 0.75, 1"
							"quick, 0.15, 0, 0.1, 1"
						];
						animation = [
							"global, 1, 10, default"
							"border, 1, 5.39, easeOutQuint"
							"windows, 1, 4.79, easeOutQuint"
							"windowsIn, 1, 4.1, easeOutQuint, popin 87%"
							"windowsOut, 1, 1.49, linear, popin 87%"
							"fadeIn, 1, 1.73, almostLinear"
							"fadeOut, 1, 1.46, almostLinear"
							"fade, 1, 3.03, quick"
							"layers, 1, 3.81, easeOutQuint"
							"layersIn, 1, 4, easeOutQuint, fade"
							"layersOut, 1, 1.5, linear, fade"
							"fadeLayersIn, 1, 1.5, linear, fade"
							"fadeLayersOut, 1, 1.39, almostLinear"
							"workspaces, 1, 1.94, almostLinear, fade"
							"workspacesIn, 1, 1.21, almostLinear, fade"
							"workspacesOut, 1, 1.94, almostLinear, fade"
						];
					};

					workspace = [
						"w[tv1], gapsout: 0, gapsin: 0"
						"1, monitor:DP-2, default:true"
						"2, monitor:DP-2"
						"3, monitor:DP-2"
						"4, monitor:DP-2"
						"5, monitor:DP-2"
						"6, monitor:DP-3, default:true"
						"7, monitor:DP-3"
						"8, monitor:DP-3"
						"9, monitor:DP-3"
						"10, monitor:DP-3"
						"1, monitor:eDP-1, default:true"
						"2, monitor:eDP-1"
						"3, monitor:eDP-1"
						"4, monitor:eDP-1"
						"5, monitor:eDP-1"
					];

					dwindle = {
						pseudotile = true;
						preserve_split = true;
					};

					# scrolling = {
					# 	fullscreen_on_one_column = true;
					# 	column_width = 0.5;
					# 	focus_fit_method = 1;
					# 	follow_focus = true;
					# 	direction = "right";
					# 	explicit_column_widths = ".5,1.";
					# };

					misc = {
						force_default_wallpaper = 0;
						disable_hyprland_logo = false;
					};

					# input
					input = {
						kb_layout = "eu";
						follow_mouse = 1;
						sensitivity = 0;
						touchpad.natural_scroll = false;
						touchpad.disable_while_typing = false;
					};

					gesture = "4, horizontal, workspace";

					# keybindings
					"$mainMod" = "SUPER";
					bind = [
						"$mainMod, Q, exec, $terminal"
						"$mainMod, C, killactive"
						"$mainMod CONTROL, M, exit"
						"$mainMod, V, togglefloating"
						"$mainMod, R, exec, $menu"
						"$mainMod, P, pseudo"
						"$mainMod, J, togglesplit"
						"$mainMod, F, exec, $fileManager"
						"$mainMod, T, fullscreen"
						"$mainMod, L, exec, hyprlock"
						# "$mainMod, Shift left, layoutmsg, swapcol l"
						# "$mainMod, Shift right, layoutmsg, swapcol r"
						# "$mainMod, O, layoutmsg, colresize +conf"
						"$mainMod, left, movefocus, l"
						"$mainMod, right, movefocus, r"
						"$mainMod, up, movefocus, u"
						"$mainMod, down, movefocus, d"
						"Alt, Tab, cyclenext, visible prev hist"
						"Alt Shift, Tab, cyclenext, visible next hist"
						"$mainMod Alt, Tab, movewindow, mon:0"
						"$mainMod, S, togglespecialworkspace, magic"
						"$mainMod SHIFT, S, movetoworkspace, special:magic"
						", Pause, pass, class:^(discord)$"
						"$mainMod, Print, exec, hyprshot -m region"
					]; # ++ (
					# 	builtins.concatLists(builtins.genList (i:
					# 		[
					# 			"$mainMod, ${toString i}, exec, hyprctl dispatch workspace $(hyprctl activeworkspace -j | jq 'if .id > 5 then ${toString i+5} else ${toString i} end')"
					# 			"$mainMod, shift, ${toString i}, exec, hyprctl dispatch movetoworkspace $(hyprctl activeworkspace -j | jq 'if .id > 5 then ${toString i+5} else ${toString i} end')"
					# 		]
					# 	))
					# );

					bindm = [
						"$mainMod, mouse:272, movewindow"
						"$mainMod, mouse:273, resizewindow"
					];

					bindel = [
						",XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
						",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
						",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
						",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
						",XF86MonBrightnessUp, exec, brightnessctl s 5%+"
						",XF86MonBrightnessDown, exec, brightnessctl s 5%-"
					];

					bindl = [
						", XF86AudioNext, exec, playerctl next"
						", XF86AudioPause, exec, playerctl play-pause"
						", XF86AudioPlay, exec, playerctl play-pause"
						", XF86AudioPrev, exec, playerctl previous"
					];

					# window rules
					windowrule = [
						# disable rounding and border for single windows
						"border_size 0, match:workspace w[tv1], match:float false"
						"rounding 0, match:workspace w[tv1], match:float false"
						# ignore maximize requests from apps
						"suppress_event maximize, match:class .*"
						# fix xwayland dragging issues
						"no_focus on, match:class ^$, match:title ^$, match:xwayland true, float on, fullscreen off, pin off"
						# godot
						"tile on, match:initial_class Godot"
						"float on, pin off, match:initial_title Godot, match:initial_class negative:Godot"
						"float on, pin off, match:initial_title negative:Godot, match:initial_class Godot"
						# main steam window
						"tile on, match:class ^(steam)$"
						"float on, match:class ^(steam)$, match:title ^()$"
						# gpu screen recorder ui
						"fullscreen on, pin on, animation off, match:initial_title ^(gsr ui)$"
						# SORS
						"float on, match:class ^(SonnensystemVorlage)$"
						# LearnOpenGL
						"float on, match:title ^(LearnOpenGL)"
						# kruler
						"float on, match:class ^(org.kde.kruler)$"
						"border_size 0, match:class ^(org.kde.kruler)$"
						"rounding 0, match:class ^(org.kde.kruler)"
						# steam games
						"fullscreen on, match:initial_class ^(steam_app_.*)$"
						# minecraft
						"tile on, match:class ^(Minecraft.*)$"
						"fullscreen on, match:class ^(Minecraft.*)$"
					];

					layerrule = [
						"no_screen_share on, match:namespace notifications"
					];

					xwayland.force_zero_scaling = true;
				};
			};
		};
	};
}
